### PR TITLE
Add social links to the collection metadata to offchain metadata

### PR DESCRIPTION
**Pull request by samyarkd**
I added social links to the collection metadata, i did not include it into the onchain metadata as i don't have enough understanding about arrays in ton.

### CODE REVIEW

**Comment by tuminzee** [comment]
@samyarkd why did you remove the /dist folder from .env?

**Comment by samyarkd** [comment]
@tuminzee  I think i did it because i needed the social links in my project and no one reviewed this issue so gave up on this and i was using my fork in my project and thus i wanted the build of the project too, i should have closed this issue.

**Comment by tuminzee** [comment]
@samyarkd I understand why you raised the PR regarding the need for social links.

However, I'd like to understand why the build folder was removed from `.gitignore`.

Regardless, here are a few things you can do to get your PR merged faster in the future:

- Check for linting/Prettier rules. If the project doesn't explicitly define these rules, it's generally assumed that you shouldn't change them unless specifically requested.
- Build folder exclusion. The build folder typically contains compiled JavaScript files generated from your TypeScript code. Since these are derived files, there's no need to include them in the repository.

**Comment by samyarkd** [comment]
@tuminzee are you one of the maintainers? I don't think they accept pr at all. The first two commits were my actual commits in this pr. But they did not review this pr at all nor give me anything.


So I started using my own build in this package, (that's why I removed the dist folder) I made my own build and deployed it directly on GitHub and pulled it from GitHub and used it in my project. 

If you are a maintainer I willa make necessary changes to this pr to be reviewed and accepted.

**Comment by samyarkd** [comment]
@tuminzee are you one of the maintainers? I don't think they accept pr at all. The first two commits were my actual commits in this pr. But they did not review this pr at all nor give me anything.


So I started using my own build in this package, (that's why I removed the dist folder) I made my own build and deployed it directly on GitHub and pulled it from GitHub and used it in my project. 

If you are a maintainer I willa make necessary changes to this pr to be reviewed and accepted.

**Comment by tuminzee** [comment]
@samyarkd I am not a maintainer of this repo. sorry to bother you.

**Pull request closed without merging**
